### ISSUE TITLE
No image render on HTCDesire 2.2 480x800 24dpi

### ISSUE THREAD

**Issue by tkxel-android** [harism/android-pagecurl#1]
Hi, I run your code at simulator it works fine with images, but when I run it on device. Only the white page is shown to me. Any way It is a very good effort.

**Comment by harism** [comment]
Thanks a bunch for your information. Unfortunately I don't have an Android device so I'm totally bound to emulator only at the moment. I'm hoping that at some point I can do some testing on actual device too though.

**Comment by tkxel-android** [comment]
Oh, Thanks. Any way This is a great code from you.

**Comment by namghiwook** [comment]
http://gamedev.stackexchange.com/questions/10829/loading-png-textures-for-use-in-android-opengl-es1

**Comment by harism** [comment]
Thanks for the link. I added scaling up to nearest power of two before setting bitmap as texture. Hope this fixes problems with textures.

**Comment by namghiwook** [comment]
Thank you for your implementation! It works on my Nexus One.

**Comment by namghiwook** [comment]
As you can see attached images, it cracks on left-top, left-bottom areas
when I flip the paper in left to right direction.

You can see this scene on the emulator.

I hope this to work perfectly in some days. And Thank you again!

2011/4/26 harism <
reply@reply.github.com>

**Comment by crafton** [comment]
confirming this also works on G1. Great work Harri.

"I added scaling up to nearest power of two before setting bitmap as texture."

Could you say what that actually does?

**Comment by tkxel-android** [comment]
I am also confirming. Its now working perfectly on my "HTC Desire 2.2". 
I really appreciate your effort.

**Comment by harism** [comment]
Thanks all for running and verifying this issue on real devices.

As for the 'cracking' I'm familiar with the problem but haven't decided yet how to overcome it. Problem is that triangle strip is constructed in 'wrong' order in some situations leaving a few polygons 'transparent'. Maybe I will switch back to using triangle indices for good. Fixing a few rendering issues is my next task in any case.

**Comment by tkxel-android** [comment]
Yes, you are write. Some time it show few white pixels triangle line form corner to the bottom.

**Comment by harism** [comment]
I did some modifications on split line algorithm and didn't see this happening any more. In one rare case, on emulator at least, there is a rendering artefact though. It happens when direction vector length is zero causing a division by zero and producing NaNs. This is not a rendering problem though but more of a problem with generating proper values within UI.

**Comment by wangpeng1** [comment]
hello,you do very well,but if  you add auto page curl effect,it more well,in other word,if i click one,it can turn page,the user experience is more good.  and i think you should accelerate flip speed. you do very well from right to left to turn page,but from left to right not good.

**Comment by wangpeng1** [comment]
if you can deal with Antialiasing,it looks more better

**Comment by harism** [comment]
I've been thinking about adding automated page flip but am concentrating on other things first. Namely to improve visual quality, especially shadows, and will get back to user interaction later on.

About antialiasing, I've noticed render quality isn't exactly as sharp as I've been hoping for but haven't found GL10 setting to fix this yet. And rendering to higher precision texture, which could be drawn to screen size later, sounds a bit heavy operation for having smooth edges. But guess it's something I have to look at eventually.

**Comment by harism** [comment]
Ah, apparently it's possible to have multisampling enabled on hardware side but since it seems rather 'tricky', and most likely doesn't work on emulator, I'm leaving everything as is for now. Using this EGLConfigChooser might do the trick though;
http://gdc2011-android-opengl.googlecode.com/svn/trunk/src/com/example/gdc11/MultisampleConfigChooser.java

**Comment by tkxel-android** [comment]
hi, Well the if you are going for auto curl effect. Please make it with a functionality e.g  view.setAutoCurl( true ) ; 
As it is depend on the user requirements. mostly the user prefer manually page curl ( I guess ) .  But other things are preferred 1st.
