### ISSUE TITLE
CurlView displaying the reverse side of image

### ISSUE THREAD

**Issue by jabuel** [harism/android-pagecurl#20]
Hi, I found an issue, 

Pre-requisite:
- CurlView is in Single display mode. Using the right to left curl

Steps to Reproduce:
- Turn the last page so that no page is displayed in CurlView.
- Jump to a certain page using setCurrentIndex

Problem:
 -Page is displayed in reverse side (But updates the correct image side after any touch event)
 -This only happens if selecting image occurred after the last page is turned

Can you please tell how to fix this? Thanks in advance,

**Comment by harism** [comment]
Should be fixed now. If you want to fix this in your own codebase, take a look on CurlView.java;

void updateBitmaps() {
...
// This line is missing.
mPageRight.setFlipTexture(false);
mPageRight.setRect(mRenderer.getPageRect(CurlRenderer.PAGE_RIGHT));
mPageRight.reset();
mRenderer.addCurlMesh(mPageRight);
...
}

**Comment by jabuel** [comment]
It worked. Thank you.
