### ISSUE TITLE
opengl es 2.0 migration

### ISSUE THREAD

**Issue by hlkyvz** [harism/android-pagecurl#26]
Is it big deal to migrate this project to open gl es 2.0 ?  I need this because I want to remove the non power of two size limitation for textures. If you don't have time for this I'll deal with it next week.

**Comment by harism** [comment]
It shouldn't be a very big task. Everything you need for OpenGL ES 2.0 is
calculated already and all you need to do is implement your own shaders.
These should't be very tricky ones. There's position, color and texture
position per vertex attributes which should make it rather simple shader.
On May 26, 2012 1:27 PM, "halukyavuz" <
reply@reply.github.com>
wrote:

**Comment by hlkyvz** [comment]
I created one shader for each CurlMesh but still all pages are drawn by the same image, essl code for shader is following.

```
private final String mVertexShader =
        "attribute vec4 aPosition;\n" +
        "attribute vec2 aTextureCoord;\n" +
        "varying vec2 vTextureCoord;\n" +
        "void main() {\n" +
        "  gl_Position = aPosition;\n" +
        "  vTextureCoord = aTextureCoord;\n" +
        "}\n";

private final String mFragmentShader =
    "precision mediump float;\n" +
    "varying vec2 vTextureCoord;\n" +
    "uniform sampler2D sTexture;\n" +
    "void main() {\n" +
    "  gl_FragColor = texture2D(sTexture, vTextureCoord);\n" +
    "}\n";
```

do you have any idea about my mistake ?

**Comment by harism** [comment]
Not really. Vertex and fragment shaders do look pretty close to what I was wondering about. Hmm.. This sounds more of a problem with binding correct texture for rendering - assuming textures are set properly for CurlPages.

I ran a very quick text using this same shader and all I had to change was;

<pre>attribute vec4 aPosition;</pre>

<pre>attribute vec3 aPosition;
  gl_Position = vec4(aPosition, 1.0);</pre>


Page aspect ratio was totally wrong though for my run but textures seemed to be ok.

**Comment by hlkyvz** [comment]
I updated shader as yours but nothing changed. Could you please send your test code if it's not problem for you? that could be a good guideline for me. I stucked in the problem of multitexture issue.

**Comment by harism** [comment]
I've had it in mind for a long while to write this code to use OpenGL ES
2.0 instead. So once I get back home I create a new branch or project and
start working on it. At first it'll be "textures only" implementation but I
will try to get it to work "properly" tomorrow latest.
On May 29, 2012 2:08 PM, "halukyavuz" <
reply@reply.github.com>
wrote:

**Comment by hlkyvz** [comment]
Okay thank you so much I'll be waiting for that.

**Comment by harism** [comment]
Ok, I put a "opengl_es_20" -branch which works for me at least. There are still some optimizations that could be done using shaders but let's see if I leave it as it is at the moment. For the sake of similarity to OpenGL 1.0 version.

**Comment by hlkyvz** [comment]
You're great! It works nice on motorola xoom. Thank you.
