### ISSUE TITLE
shadow center of pages(left and right)

### ISSUE THREAD

**Issue by jaykumarhk1** [harism/android-pagecurl#39]
Dear Hairson,
First of all I would like to thank you and really appreciate your work. One needed one help from your side. My boss wants to see the shown between the pages(left and right), as it looks like real book.
can you help me?
Thanks

**Comment by saitomea** [comment]
You could change the background image created in `PageProvider.loadBitmap(int width, int height, int index)` to create a 2D shadow.

**Comment by jaykumarhk1** [comment]
Thx, I need another help, and thats I want to put background image behind it. how to do it?
as you have provided method of setbackgroundColor.

**Comment by saitomea** [comment]
https://github.com/harism/android_page_curl/issues/27

I tried and it worked. Just set the background color using `mCurlView.setBackgroundColor(Color.TRANSPARENT);` and  do the steps described in the post to have a trasparent background.

This is how my init method code ended up like:

```
    private void init(Context ctx) {
        mRenderer = new CurlRenderer(this);
        setEGLConfigChooser(8, 8, 8, 8, 16, 0);
        setRenderer(mRenderer);
        setRenderMode(GLSurfaceView.RENDERMODE_WHEN_DIRTY);
        getHolder().setFormat(PixelFormat.TRANSLUCENT);
        setZOrderOnTop(true);
        setOnTouchListener(this);

        // Even though left and right pages are static we have to allocate room
        // for curl on them too as we are switching meshes. Another way would be
        // to swap texture ids only.
        mPageLeft = new CurlMesh(10);
        mPageRight = new CurlMesh(10);
        mPageCurl = new CurlMesh(10);
        mPageLeft.setFlipTexture(true);
        mPageRight.setFlipTexture(false);
    }
```

**Comment by jaykumarhk1** [comment]
Thank you very much ..!!! done
